doctrine:
    dbal:
        host: '%env(resolve:POSTGRES_HOST)%'
        dbname: '%env(resolve:POSTGRES_DB)%'
        server_version: '%env(resolve:POSTGRES_VERSION)%'
        user: '%env(resolve:POSTGRES_USER)%'
        password: '%env(resolve:POSTGRES_PASSWORD)%'
        port: '%env(resolve:POSTGRES_PORT)%'
        driver: pdo_pgsql
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
