framework:
    router:
        utf8: true
    php_errors:
        log: true
    cache:
        default_redis_provider: 'redis://%env(resolve:REDIS_PASSWORD)%@%env(resolve:REDIS_HOST)%:%env(resolve:REDIS_PORT)%/%env(resolve:REDIS_DB_INDEX)%'
        pools:
            cache.mycache:
                adapter: cache.adapter.redis
        app: cache.mycache
        system: cache.mycache
    validation:
        enable_annotations: true
    serializer:
        enable_annotations: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
