security:
    role_hierarchy:
        ROLE_COURIER: [ ROLE_CONSUMER ]
        ROLE_SELLER: [ ROLE_COURIER ]
    encoders:
        Symfony\Component\Security\Core\User\User: 'plaintext'
    providers:
        api_users:
            memory:
                users:
                    consumer:
                        password: 'consumer'
                        roles: 'ROLE_CONSUMER'
                    courier:
                        password: 'courier'
                        roles: 'ROLE_COURIER'
                    seller:
                        password: 'seller'
                        roles: 'ROLE_SELLER'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Secured Area
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
