parameters:
    app_env: '%env(resolve:APP_ENV)%'
    rpm: '%env(resolve:RPM)%'
    products_service_url: '%env(resolve:PRODUCTS_API_URL)%'
    logistic_service_url: '%env(resolve:LOGISTIC_API_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true


    data_time_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags: [ serializer.normalizer ]

    App\DataFixtures\:
        resource: '../src/DataFixtures/'
        tags: [ 'doctrine.fixture.orm' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/ArgumentResolver/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/DTO/'
            - '../src/DataFixtures'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Utils\RateLimiter:
        arguments:
            $rpm: '%rpm%'
            $appEnv: '%app_env%'
    App\ArgumentResolver\RequestDataResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\APIHelper\ProductsAPIHelper:
        arguments:
            $apiUrl: '%products_service_url%'
    App\APIHelper\LogisticAPIHelper:
        arguments:
            $apiUrl: '%logistic_service_url%'


